const questionRows = [
  [
    1,
    "4.1",
    "Understanding the organization and its context",
    "Has the organization identified relevant internal and external issues affecting the QMS?",
    "yes",
  ],
  [
    2,
    "4.1",
    "Understanding the organization and its context",
    "Are the identified internal and external issues relevant to the organization’s purpose and strategic direction?",
    "no",
  ],
  [
    3,
    "4.1",
    "Understanding the organization and its context",
    "Are the identified internal and external issues periodically monitored and reviewed?",
    "no",
  ],
  [
    4,
    "4.2",
    "Understanding the Needs and Expectations of Interested Parties",
    "Has the organization identified the relevant interested parties and their applicable requirements related to the QMS?",
    "no",
  ],
  [
    5,
    "4.2",
    "Understanding the Needs and Expectations of Interested Parties",
    "Are the interested parties and their relevant requirements regularly monitored and reviewed?",
    "no",
  ],
  [
    6,
    "4.3",
    "Determining the Scope of the QMS",
    "Has the organization clearly defined the boundaries and applicability of the QMS?",
    "no",
  ],
  [
    7,
    "4.3",
    "Determining the Scope of the QMS",
    "Does the QMS scope consider relevant internal and external issues?",
    "no",
  ],
  [
    8,
    "4.3",
    "Determining the Scope of the QMS",
    "Does the QMS scope consider the requirements of relevant interested parties?",
    "yes",
  ],
  [
    9,
    "4.3",
    "Determining the Scope of the QMS",
    "Does the QMS scope clearly identify the products and services covered?",
    "no",
  ],
  [
    10,
    "4.3",
    "Determining the Scope of the QMS",
    "Is the QMS scope maintained as documented information and readily available?",
    "no",
  ],
  [
    11,
    "4.3",
    "Determining the Scope of the QMS",
    "Are any exclusions/non-applicable ISO 9001 requirements identified and justified?",
    "no",
  ],
  [
    12,
    "4.4",
    "QMS and Its Processes",
    "Has the organization identified and implemented the required QMS processes?",
    "no",
  ],
  [
    13,
    "4.4",
    "QMS and Its Processes",
    "Has the organization defined the inputs and outputs of each process?",
    "no",
  ],
  [
    14,
    "4.4",
    "QMS and Its Processes",
    "Has the organization defined the order of its processes and how they interact?",
    "no",
  ],
  [
    15,
    "4.4",
    "QMS and Its Processes",
    "Does the organization monitor and measure process performance?",
    "no",
  ],
  [
    16,
    "4.4",
    "QMS and Its Processes",
    "Has the organization provided adequate resources and assigned responsibilities?",
    "no",
  ],
  [
    17,
    "4.4",
    "QMS and Its Processes",
    "Has the organization identified and addressed risks and opportunities?",
    "no",
  ],
  [
    18,
    "4.4",
    "QMS and Its Processes",
    "Does the organization review and improve processes and maintain required documents and records?",
    "no",
  ],
  [
    19,
    "5.1",
    "Leadership and commitment",
    "Does top management take responsibility for the effectiveness of the QMS?",
    "no",
  ],
  [
    20,
    "5.1",
    "Leadership and commitment",
    "Are the quality policy and quality objectives aligned with the organization’s direction?",
    "no",
  ],
  [
    21,
    "5.1",
    "Leadership and commitment",
    "Are QMS requirements included in the organization’s regular activities?",
    "no",
  ],
  [
    22,
    "5.1",
    "Leadership and commitment",
    "Does top management promote process-based and risk-based thinking?",
    "no",
  ],
  [
    23,
    "5.1",
    "Leadership and commitment",
    "Does top management ensure adequate resources for the QMS?",
    "no",
  ],
  [
    24,
    "5.1",
    "Leadership and commitment",
    "Does top management communicate the importance of quality and QMS requirements?",
    "no",
  ],
  [
    25,
    "5.1",
    "Leadership and commitment",
    "Does top management ensure that the QMS achieves its intended results?",
    "no",
  ],
  [
    26,
    "5.1",
    "Leadership and commitment",
    "Does top management support and involve employees in achieving QMS requirements?",
    "no",
  ],
  [
    27,
    "5.1",
    "Leadership and commitment",
    "Does top management promote continual improvement and support responsible managers?",
    "no",
  ],
  [
    28,
    "5.1.2",
    "Customer Focus",
    "Are customer requirements clearly identified and understood?",
    "no",
  ],
  [
    29,
    "5.1.2",
    "Customer Focus",
    "Are applicable statutory and regulatory requirements identified and met?",
    "no",
  ],
  [
    30,
    "5.1.2",
    "Customer Focus",
    "Are risks and opportunities affecting products and services identified and addressed?",
    "no",
  ],
  [
    31,
    "5.1.2",
    "Customer Focus",
    "Are actions taken to improve customer satisfaction?",
    "no",
  ],
  [
    32,
    "5.1.2",
    "Customer Focus",
    "Is customer satisfaction regularly monitored and reviewed?",
    "no",
  ],
  [
    33,
    "5.2.1 / 5.2.2",
    "Establishing and Communicating the Quality Policy",
    "Is the quality policy appropriate to the organization’s purpose and direction?",
    "yes",
  ],
  [
    34,
    "5.2.1 / 5.2.2",
    "Establishing and Communicating the Quality Policy",
    "Does the quality policy support the setting of quality objectives?",
    "yes",
  ],
  [
    35,
    "5.2.1 / 5.2.2",
    "Establishing and Communicating the Quality Policy",
    "Does the quality policy include commitments to meet applicable requirements and continual improvement?",
    "yes",
  ],
  [
    36,
    "5.2.1 / 5.2.2",
    "Establishing and Communicating the Quality Policy",
    "Is the quality policy documented, communicated, and understood by employees?",
    "yes",
  ],
  [
    37,
    "5.2.1 / 5.2.2",
    "Establishing and Communicating the Quality Policy",
    "Is the quality policy available to relevant interested parties, where appropriate?",
    "yes",
  ],
  [
    38,
    "5.3",
    "Organizational Roles, Responsibilities and Authorities",
    "Are QMS roles, responsibilities, and authorities clearly assigned, communicated, and understood?",
    "no",
  ],
  [
    39,
    "5.3",
    "Organizational Roles, Responsibilities and Authorities",
    "Is responsibility assigned to ensure QMS compliance and effective process performance?",
    "no",
  ],
  [
    40,
    "5.3",
    "Organizational Roles, Responsibilities and Authorities",
    "Is responsibility assigned to report QMS performance, identify improvement opportunities, and promote customer focus?",
    "no",
  ],
  [
    41,
    "5.3",
    "Organizational Roles, Responsibilities and Authorities",
    "Is responsibility assigned to maintain QMS integrity when changes are planned and implemented?",
    "no",
  ],
];

export const questions = questionRows.map(
  ([id, clause, section, question, answer]) => ({
    id,
    clause,
    section,
    question,
    answer,
    evidence: "",
  }),
);
